export const colors = {
  purple: "#A238FF",
  black: "black",
  white: "white",
  red: "#ff0000",
  yellow: "#ffed00",
  magenta: "#ff0092",
  lime: "#c2ff00",
  blue: "#00c7f2",
  lightBlue: "#c1f1fc",
  lightGreen: "#ebffac",
  lightPink: "#ffc2e5",
  lightRed: "#ffaaaa",
  background: "#f5f2f8",
  backgroundHover: "#DCD9DF",
  backgroundBorderMain: "#c2c0c4",
  backgroundBorderSecondary: "#e1dde4",
  textPrimary: "black",
  textSecondary: "#6f6d71",
};
